// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-y4XvDYDBHw1Di52FoAS7gB186lOLY3I',
    appId: '1:221486222971:web:a3133be14ee60cc6b19cde',
    messagingSenderId: '221486222971',
    projectId: 'alleventsapp-ce448',
    authDomain: 'alleventsapp-ce448.firebaseapp.com',
    storageBucket: 'alleventsapp-ce448.firebasestorage.app',
    measurementId: 'G-1MVBBRRVYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsOtSNEVEbRbIpmIwrxCJ9sUdc-YfeYnU',
    appId: '1:221486222971:android:dbd4f31d9571c4f6b19cde',
    messagingSenderId: '221486222971',
    projectId: 'alleventsapp-ce448',
    storageBucket: 'alleventsapp-ce448.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW9xakXQuiy1Y-Mg2U41JLD0NJ-bApyZc',
    appId: '1:221486222971:ios:8270f102ce370410b19cde',
    messagingSenderId: '221486222971',
    projectId: 'alleventsapp-ce448',
    storageBucket: 'alleventsapp-ce448.firebasestorage.app',
    androidClientId: '221486222971-b4iv3ognsvtr0iikc9vm1h4r2u97n7aj.apps.googleusercontent.com',
    iosClientId: '221486222971-u0pgqa12gtvtukbns0pqmcm2ahk9aj4u.apps.googleusercontent.com',
    iosBundleId: 'com.alleventsapp.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-y4XvDYDBHw1Di52FoAS7gB186lOLY3I',
    appId: '1:221486222971:web:a3d148f581674048b19cde',
    messagingSenderId: '221486222971',
    projectId: 'alleventsapp-ce448',
    authDomain: 'alleventsapp-ce448.firebaseapp.com',
    storageBucket: 'alleventsapp-ce448.firebasestorage.app',
    measurementId: 'G-Q9E5ELVP31',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW9xakXQuiy1Y-Mg2U41JLD0NJ-bApyZc',
    appId: '1:221486222971:ios:8270f102ce370410b19cde',
    messagingSenderId: '221486222971',
    projectId: 'alleventsapp-ce448',
    storageBucket: 'alleventsapp-ce448.firebasestorage.app',
    androidClientId: '221486222971-b4iv3ognsvtr0iikc9vm1h4r2u97n7aj.apps.googleusercontent.com',
    iosClientId: '221486222971-u0pgqa12gtvtukbns0pqmcm2ahk9aj4u.apps.googleusercontent.com',
    iosBundleId: 'com.alleventsapp.com',
  );

}